services:
  web:
    build: 
      context: ./django
    image: yigamarkgabriel333288/django_test_web:v1.0.0.0
    container_name: "django_test_web"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn demo.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django/:/usr.src/app
      - static_files:/usr/src/app/staticfiles
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
    image: yigamarkgabriel333288/django_test_nginx:v1.0.0.0
    container_name: "django_test_nginx"
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles

volumes:
  static_files:

  # dns:
  #   build:
  #     context: ./dns/
  #   restart: always
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   volumes:
  #     - ./dns/named.conf:/etc/bind/named.conf
  #     - ./dns/zone/:/etc/bind/zone/
  #   command: named -c /etc/bind/named.conf -g -u named